# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WebService-Bloglines-Blogroll
version:      0.02
version_from: lib/WebService/Bloglines/Blogroll.pm
installdirs:  site
requires:
    Carp:                          0
    LWP::Simple:                   1.1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
